apiVersion: v1
kind: Service
metadata:
  name: {{ template "subchart.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "subchart.chart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
