apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-mysql-dev
  namespace: argocd
spec:
  project: default
  source:
    path: wordpress-mysql
    repoURL: https://github.com/marton-szabo-epam/gitops-argocd.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-mysql-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
      prune: true