apiVersion: v1
metadata:
  name: mysql-pass
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "subchart.chart" . }}
    release: {{ .Release.Name }}
data:
  password: TXEyRCMoOGdmMDk=
kind: Secret
type: Opaque